# Generated by Django 3.1.7 on 2021-03-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('data_sci', 'Data Science'), ('automation', 'Automation'), ('hardware', 'Hardware'), ('medicine', 'Medicine'), ('misc', 'Miscellaneous')], default='misc', max_length=200),
        ),
    ]
