# Generated by Django 3.1.7 on 2021-03-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210314_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('year_published', models.IntegerField()),
                ('article_type', models.CharField(choices=[('manuscript', 'Manuscript'), ('abstract', 'Abstract')], default='abstract', max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('doi', models.URLField()),
                ('journal_link', models.URLField()),
                ('download_link', models.URLField()),
            ],
        ),
    ]
