# Generated by Django 3.1.7 on 2021-03-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
