# Generated by Django 3.1.7 on 2021-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('web-dev', 'Web Development'), ('data-sci', 'Data Science'), ('automation', 'Automation'), ('hardware', 'Hardware'), ('medicine', 'Medicine'), ('misc', 'Miscellaneous'), ('', 'None')], default='', max_length=200),
        ),
    ]
