# Generated by Django 3.1.7 on 2021-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210313_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(default=models.CharField(max_length=200, unique=True), max_length=255),
        ),
    ]
